### ISSUE TITLE
Resource prefix doesn't apply to many resources.

### ISSUE THREAD

**Issue by MorganPattersonSignet** [aws-samples/aws-health-events-insight#9]
`ResourcePrefix` is applied to very few resources out of the box, causing naming collisions when deploying twice in the same AWS account.

# Use case
Deploy the `DataCollection` stack(s) twice in the same account for a production and non-production system.

# Expected Behavior
Successfully deploy once with a `ResourcePrefix` like `Heidi-Test-` and another with `Heidi-Prod-` in the same account, and not have them interfere with one another.

# Actual behavior
Several naming collisions from hard-coded or un-prefixed resources.

# What I tried
I tried adding the `ResourcePrefix` anywhere it made sense throughout the stack, but had a very hard time doing so.

**Comment by bajwkanw** [comment]
Acked. We have added this in our backlog and will update soon. Thankyou

**Comment by bajwkanw** [comment]
Fixed

**Comment by MorganPattersonSignet** [comment]
While the infrastructure does now spin up (thx!), the data sources are still "cross-contaminating".

My use case involved something like this

Dev-Heidi receives health events from:
- Test accounts
- Dev accounts


Prod-Heidi receives health events from:
- Staging Accounts
- Prod accounts

I'd like to keep the infrastructure AND the data separate for these.

**Comment by bajwkanw** [comment]
If you have a single payer for both Dev and Prod and have enabled org view, the feed from the default EventBridge event bus containing health events will include data for all accounts under that payer. You can filter this data using an EventBridge rule on the data collection bus.
